// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Route4MoviePlug.Api.Data;

#nullable disable

namespace Route4MoviePlug.Api.Data.Migrations
{
    [DbContext(typeof(Route4DbContext))]
    partial class Route4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Benefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SplashPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SplashPageId");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Exclusive footage from set, rehearsals, and production meetings",
                            DisplayOrder = 1,
                            Icon = "🎬",
                            SplashPageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Behind-the-Scenes Content"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Access to screenplay drafts, revisions, and director's notes",
                            DisplayOrder = 2,
                            Icon = "📝",
                            SplashPageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Script Development"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Description = "Weekly updates from cast and crew throughout filming",
                            DisplayOrder = 3,
                            Icon = "🎥",
                            SplashPageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Production Diaries"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Direct Q&A sessions with filmmakers and cast members",
                            DisplayOrder = 4,
                            Icon = "💬",
                            SplashPageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Title = "Interactive Community"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.CastingCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HowToRespond")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RolesDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShortUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ToneAndIntent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CastingCalls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            BackgroundImageUrl = "assets/clients/making-of-mary/cover.jpg",
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Constraints = "This is not a traditional audition. This is not a networking event. This is an invitation to witness and participate in world formation without exposition.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HowToRespond = "Responses are accepted through private intake form below. Responses are reviewed deliberately. No social media engagement. No public discussion.",
                            IsActive = true,
                            ProjectStatus = "Script complete. Pre-production underway.",
                            RolesDescription = "Seeking actors and crew for participation in a process-first production. No outcomes revealed. No character arcs disclosed. Participation is presence, not performance.",
                            Title = "Signal I — Casting Call",
                            ToneAndIntent = "Episodic indie project. Restrained. Intentional. No context, only craft."
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.CastingCallResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CastingCallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleInterest")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CastingCallId");

                    b.ToTable("CastingCallResponses");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThemeAccentColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThemeFontFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThemeFontSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThemePrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exclusive behind-the-scenes documentary film project",
                            IsActive = true,
                            Name = "Making of MARY",
                            Slug = "making-of-mary"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiscordConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProcessRoom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordConfigurationId", "ChannelId")
                        .IsUnique();

                    b.ToTable("DiscordChannels");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BotToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuildId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LanguagePack")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("DiscordConfigurations");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DiscordConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiscordConfigurationId", "RoleId")
                        .IsUnique();

                    b.ToTable("DiscordRoles");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DocumentDestructionMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DestroyedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestroyedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentDestructionMetadata");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClientAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlatformFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.MembershipTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceInterval")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagLine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Pay per signal witnessed. Discover anonymous pre-artifacts and fragments as they emerge without ongoing subscriptions.",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Signal Discovery",
                            Price = 7.50m,
                            PriceInterval = "per-signal",
                            TagLine = "Cross the threshold to witness"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Pay per writing table, shot council, or process session attended. Witness the creative process without story outcomes.",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Ritual Participation",
                            Price = 20.00m,
                            PriceInterval = "per-session",
                            TagLine = "Witness process, not outcomes"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Pay per private viewing event attended. Exclusive offline-safe access in protected locations with verified witness status.",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Private Viewing",
                            Price = 35.00m,
                            PriceInterval = "per-viewing",
                            TagLine = "Sacred witness moments"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MembershipTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MembershipTierId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlaybackEmbedUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProviderAssetId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ReleaseInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInstanceId");

                    b.ToTable("ReleaseArtifacts");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ReleaseCycleTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full ritual sequence for Making of Mary episodes",
                            IsActive = true,
                            Name = "Mary Episode Release Cycle"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReleaseCycleTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCycleTemplateId");

                    b.HasIndex("ClientId", "Key")
                        .IsUnique();

                    b.ToTable("ReleaseInstances");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ReleaseInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInstanceId");

                    b.ToTable("ReleaseStageExecutions");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscordChannelTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsDiscordIntegrated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReleaseCycleTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresWitnessRole")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCycleTemplateId");

                    b.ToTable("ReleaseStageTemplates");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStateTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnouncementSent")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscordChannelsLocked")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DiscordChannelsOpened")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FromStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReleaseInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransitionReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ReleaseInstanceId");

                    b.ToTable("ReleaseStateTransitions");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.RitualMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnouncementMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("AutomaticallyLockChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("AutomaticallyUnlockChannel")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBeSkipped")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloseTrigger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosingMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultDurationHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableExternalEmojis")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableFileUploads")
                        .HasColumnType("bit");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("NotesForAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OpenTrigger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReleaseCycleTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("RequiredRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RitualName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SlowModeSeconds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetChannelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetChannelPurpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisibilityLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseCycleTemplateId");

                    b.HasIndex("ClientId", "ReleaseCycleTemplateId", "RitualName")
                        .IsUnique();

                    b.ToTable("RitualMappings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-1111-1111-1111-111111111111"),
                            AnnouncementMessage = "⚒️ **PROCESS OPEN** — The room is now open. Decisions, not outcomes. Craft, not results.",
                            AutomaticallyLockChannel = true,
                            AutomaticallyUnlockChannel = true,
                            CanBeSkipped = true,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloseTrigger = "DurationExpired",
                            ClosingMessage = "✅ Process session complete. The room is now closed.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDurationHours = 3,
                            Description = "Witness-only process rooms (Writing Table, Shot Council, etc.)",
                            DisableExternalEmojis = false,
                            DisableFileUploads = true,
                            ExecutionOrder = 2,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = false,
                            OpenTrigger = "Manual",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RequiredRoles = "[\"CoreTeam\",\"Witness\"]",
                            RitualName = "Process",
                            SlowModeSeconds = "10",
                            StageType = "Process",
                            TargetChannelPurpose = "process",
                            VisibilityLevel = "L1"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-2222-2222-222222222222"),
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = false,
                            CanBeSkipped = false,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloseTrigger = "DurationExpired",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDurationHours = 24,
                            Description = "Intentional silence before the drop",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 3,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "PreviousStageCompleted",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RitualName = "Hold",
                            StageType = "Hold",
                            TargetChannelPurpose = "signal",
                            VisibilityLevel = "L2"
                        },
                        new
                        {
                            Id = new Guid("66666666-3333-3333-3333-333333333333"),
                            AnnouncementMessage = "📺 **THE DROP** — The episode is here. Read-only for 24 hours. Experience it first.",
                            AutomaticallyLockChannel = true,
                            AutomaticallyUnlockChannel = true,
                            CanBeSkipped = false,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloseTrigger = "DurationExpired",
                            ClosingMessage = "The 24-hour window has closed. Reflection begins.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDurationHours = 24,
                            Description = "Primary episode release",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 4,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "ScheduledTime",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RitualName = "Drop",
                            StageType = "Drop",
                            TargetChannelPurpose = "releases",
                            VisibilityLevel = "L3"
                        },
                        new
                        {
                            Id = new Guid("66666666-4444-4444-4444-444444444444"),
                            AnnouncementMessage = "💬 **ECHO** — Reflection is open. What did you notice? No spoilers. No theories. Only presence.",
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = true,
                            CanBeSkipped = false,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CloseTrigger = "Manual",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDurationHours = 72,
                            Description = "Post-drop reflection (no spoilers, no theories)",
                            DisableExternalEmojis = false,
                            DisableFileUploads = true,
                            ExecutionOrder = 5,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = false,
                            OpenTrigger = "PreviousStageCompleted",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RequiredRoles = "[\"Witness\",\"Member\"]",
                            RitualName = "Echo",
                            SlowModeSeconds = "30",
                            StageType = "Echo",
                            TargetChannelPurpose = "reflection",
                            VisibilityLevel = "L3"
                        },
                        new
                        {
                            Id = new Guid("66666666-5555-5555-5555-555555555555"),
                            AnnouncementMessage = "🎬 **FRAGMENTS** — Behind-the-scenes residue. No context. Just artifacts.",
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = false,
                            CanBeSkipped = true,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "BTS residue and artifacts",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 6,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "Manual",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RequiredRoles = "[\"CoreTeam\"]",
                            RitualName = "Fragments",
                            StageType = "Fragments",
                            TargetChannelPurpose = "fragments",
                            VisibilityLevel = "L2"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AnnouncementMessage = "🎙️ **INTERVAL** — Meta reflection podcast is live.",
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = true,
                            CanBeSkipped = true,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Podcast and meta reflection",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 7,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "Manual",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RitualName = "Interval",
                            StageType = "Interval",
                            TargetChannelPurpose = "interval",
                            VisibilityLevel = "L3"
                        },
                        new
                        {
                            Id = new Guid("66666666-7777-7777-7777-777777777777"),
                            AnnouncementMessage = "🎟️ **PRIVATE VIEWING** — Invitations for Witness-only screening have been sent.",
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = false,
                            CanBeSkipped = true,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Witness-only private screening",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 8,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "Manual",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RequiredRoles = "[\"Witness\"]",
                            RitualName = "PrivateViewing",
                            StageType = "PrivateViewing",
                            TargetChannelPurpose = "invitations",
                            VisibilityLevel = "L1"
                        },
                        new
                        {
                            Id = new Guid("66666666-8888-8888-8888-888888888888"),
                            AutomaticallyLockChannel = false,
                            AutomaticallyUnlockChannel = false,
                            CanBeSkipped = false,
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Permanent record and canon",
                            DisableExternalEmojis = false,
                            DisableFileUploads = false,
                            ExecutionOrder = 9,
                            IsActive = true,
                            IsAnonymous = false,
                            IsReadOnly = true,
                            OpenTrigger = "PreviousStageCompleted",
                            ReleaseCycleTemplateId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RitualName = "Archive",
                            StageType = "Archive",
                            TargetChannelPurpose = "releases",
                            VisibilityLevel = "L3"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.SplashPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("SplashPages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Get unprecedented access to the entire film making process of MAKING OF MARY. Join our exclusive community and witness every step of the creative journey.",
                            IsPublished = true,
                            Subtitle = "Go Behind the Scenes",
                            Title = "Exclusive VIP Membership"
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.StripeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApplicationFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("StripeAccountId")
                        .IsUnique();

                    b.ToTable("StripeAccounts");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.TierFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.ToTable("TierFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000001"),
                            DisplayOrder = 1,
                            IsHighlighted = true,
                            Text = "Anonymous signal drops as they emerge",
                            TierId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000002"),
                            DisplayOrder = 2,
                            IsHighlighted = false,
                            Text = "BTS fragments without story context",
                            TierId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000003"),
                            DisplayOrder = 3,
                            IsHighlighted = false,
                            Text = "Tools, hands, rooms — no explanations",
                            TierId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000004"),
                            DisplayOrder = 4,
                            IsHighlighted = false,
                            Text = "Pay only when you choose to witness",
                            TierId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000005"),
                            DisplayOrder = 5,
                            IsHighlighted = false,
                            Text = "No subscriptions, no ongoing fees",
                            TierId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000006"),
                            DisplayOrder = 1,
                            IsHighlighted = true,
                            Text = "Writing table sessions (decisions, not outcomes)",
                            TierId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000007"),
                            DisplayOrder = 2,
                            IsHighlighted = true,
                            Text = "Shot council participation (process preview)",
                            TierId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000008"),
                            DisplayOrder = 3,
                            IsHighlighted = false,
                            Text = "Color/edit sessions without story reveals",
                            TierId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-000000000009"),
                            DisplayOrder = 4,
                            IsHighlighted = false,
                            Text = "Reflection channels after ritual participation",
                            TierId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000a"),
                            DisplayOrder = 5,
                            IsHighlighted = false,
                            Text = "Pay per session attended, not time-based",
                            TierId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000b"),
                            DisplayOrder = 1,
                            IsHighlighted = true,
                            Text = "Private location screenings (QR-based access)",
                            TierId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000c"),
                            DisplayOrder = 2,
                            IsHighlighted = false,
                            Text = "Offline-safe viewing with verified witness status",
                            TierId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000d"),
                            DisplayOrder = 3,
                            IsHighlighted = false,
                            Text = "No recording, no sharing — sacred witness moments",
                            TierId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000e"),
                            DisplayOrder = 4,
                            IsHighlighted = false,
                            Text = "Invitation-only events for proven participants",
                            TierId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-00000000000f"),
                            DisplayOrder = 5,
                            IsHighlighted = false,
                            Text = "Pay only when invited and you choose to attend",
                            TierId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.WitnessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiscordChannelId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReleaseInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseInstanceId");

                    b.ToTable("WitnessEvents");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Benefit", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.SplashPage", "SplashPage")
                        .WithMany("Benefits")
                        .HasForeignKey("SplashPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SplashPage");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.CastingCall", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany("CastingCalls")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.CastingCallResponse", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.CastingCall", "CastingCall")
                        .WithMany("Responses")
                        .HasForeignKey("CastingCallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastingCall");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordChannel", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.DiscordConfiguration", "DiscordConfiguration")
                        .WithMany("Channels")
                        .HasForeignKey("DiscordConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordConfiguration");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordConfiguration", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithOne("DiscordConfiguration")
                        .HasForeignKey("Route4MoviePlug.Api.Models.DiscordConfiguration", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordRole", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.DiscordConfiguration", "DiscordConfiguration")
                        .WithMany("Roles")
                        .HasForeignKey("DiscordConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordConfiguration");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Invoice", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.MembershipTier", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Payment", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Route4MoviePlug.Api.Models.MembershipTier", "MembershipTier")
                        .WithMany()
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseArtifact", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseInstance", "ReleaseInstance")
                        .WithMany("Artifacts")
                        .HasForeignKey("ReleaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseInstance");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseInstance", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", "ReleaseCycleTemplate")
                        .WithMany()
                        .HasForeignKey("ReleaseCycleTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReleaseCycleTemplate");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStageExecution", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseInstance", "ReleaseInstance")
                        .WithMany("StageExecutions")
                        .HasForeignKey("ReleaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseInstance");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStageTemplate", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", "ReleaseCycleTemplate")
                        .WithMany("Stages")
                        .HasForeignKey("ReleaseCycleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseCycleTemplate");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseStateTransition", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseInstance", "ReleaseInstance")
                        .WithMany()
                        .HasForeignKey("ReleaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseInstance");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.RitualMapping", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", "ReleaseCycleTemplate")
                        .WithMany()
                        .HasForeignKey("ReleaseCycleTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReleaseCycleTemplate");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.SplashPage", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany("SplashPages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.StripeAccount", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.TierFeature", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.MembershipTier", "Tier")
                        .WithMany("Features")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.WitnessEvent", b =>
                {
                    b.HasOne("Route4MoviePlug.Api.Models.ReleaseInstance", "ReleaseInstance")
                        .WithMany("WitnessEvents")
                        .HasForeignKey("ReleaseInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseInstance");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.CastingCall", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.Client", b =>
                {
                    b.Navigation("CastingCalls");

                    b.Navigation("DiscordConfiguration");

                    b.Navigation("SplashPages");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.DiscordConfiguration", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.MembershipTier", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseCycleTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.ReleaseInstance", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("StageExecutions");

                    b.Navigation("WitnessEvents");
                });

            modelBuilder.Entity("Route4MoviePlug.Api.Models.SplashPage", b =>
                {
                    b.Navigation("Benefits");
                });
#pragma warning restore 612, 618
        }
    }
}
